config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root 'pages#main'
  devise_for :parents, :controllers => { registrations: 'registrations' }
  resources :parents, only: :show do
    resources :children do
      resources :tasks
    end
  end
  get '/parents/:parent_id/children/:child_id/tasks_after' => 'tasks#after_date', as: 'parent_child_tasks_date'
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "Parent"
  belongs_to :rateable, :polymorphic => true
end

app/models/child.rb
class Child < ActiveRecord::Base
  extend FriendlyId
  has_attached_file :avatar, styles: { medium: "152x152#" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  validates :name, presence: true

  belongs_to :parent
  has_many :tasks, dependent: :destroy

  friendly_id :name, use: [:slugged, :finders]

  def should_generate_new_friendly_id?
    new_record?
  end
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/parent.rb
class Parent < ActiveRecord::Base
  extend FriendlyId
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :children, dependent: :destroy
  ratyrate_rater
  friendly_id :parent_name, use: [:slugged, :finders]

  validates :parent_name, presence: true

  def should_generate_new_friendly_id?
    new_record?
  end
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "Parent"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :child
  ratyrate_rateable 'mark'

  scope :after_date, ->(date) { where('updated_at > ?', date) }

  def start_time
    self.created_at
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper :all

  def after_sign_in_path_for(resource)
    current_parent
  end

  def after_sign_up_path_for(resource)
    current_parent
  end
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  before_action :find_child, only: :show

  def show
    @tasks = @child.tasks.order(:status)
    @uncompleted_tasks = @tasks.select { |task| task.status == false }
    @completed_tasks = @tasks.select { |task| task.status == true }

    respond_to do |format|
      format.json { render json: @child }
      format.html # show.html.erb
    end
  end

  def new
    @child = current_parent.children.build
  end

  def create
    @child = current_parent.children.build(child_params)

    if @child.save
      flash[:success] = "Your child has been added!"
      redirect_to root_path
    else
      flash.now[:alert] = "Your child couldn't be added! Please check the form"
      render :new
    end
  end

  private

  def find_child
    @child = Child.find(params[:id])
  end

  def child_params
    params.require(:child).permit(:name, :age, :avatar)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def main
    if parent_signed_in?
      redirect_to current_parent
    end
  end
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  #before_filter :check_parent, only: :show
  before_action :find_parent
  before_action :authenticate_parent!

  def show
    @children = @parent.children

    respond_to do |format|
      format.json { render json: @parent }
      format.html # show.html.erb
    end
  end

  private

  def check_parent
    unless current_parent.parent_name.downcase == params[:id].to_s
      flash[:alert] = "That account doesn't belong to you!"
      redirect_to root_path
    end
  end

  def find_parent
    @parent = Parent.find(params[:id])
  end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if parent_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_parent, params[:dimension]

      update_task

      render :json => true
    else
      render :json => false
    end
  end

  private

  def update_task
    task = Task.find(params[:id])
    task.mark = params[:score].to_f
    task.status = true
    task.save
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:parent).permit(:email, :parent_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:parent).permit(:email, :parent_name, :password, :password_confirmation, :current_password)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_child, only: [:index, :new, :create]
  before_action :find_task, only: [:show, :edit, :update]

  def index
    @tasks = @child.tasks
    respond_to do |format|
      format.json { render json: @tasks }
    end
  end

  def after_date
    date = Time.parse(params[:date]) if params[:date]
    date ||= Time.current
    @tasks = Task.after_date(date)
    respond_to do |format|
      format.json { render json: @tasks }
    end
  end

  def show
    respond_to do |format|
      format.json { render json: @task }
      format.html # show.html.erb
    end
  end

  def new
    @task = @child.tasks.build
  end

  def create
    @task = @child.tasks.build(task_params)
    @task.status = false

    if @task.save
      flash[:success] = "Your task has been added!"
      redirect_to parent_child_path(@child.parent, @child)
    else
      flash.now[:alert] = "Your task couldn't be added! Please check the form"
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to @task
    end
  end

  private

  def find_child
    @child = Child.find(params[:child_id])
  end

  def find_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:summary, :description, :mark)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def profile_avatar_select(child)
    return image_tag child.avatar.url(:medium), id: 'image-preview', class: 'img-responsive img-circle profile-image' if child.avatar.exists?
    image_tag 'default-avatar.jpg', id: 'image-preview', class: 'img-responsive img-circle profile-image'
  end

  def current_user
    current_parent
  end
end

app/views/children/_form.html.haml
= render 'layouts/return'
.children-wrapper
  .child
    .image-wrap
      = simple_form_for @child, url: parent_children_path, html: { multipart: true } do |f|
        .row
          .col-md-12.text-center
            = f.error_notification
        .row
          .col-md-12.text-center
            .form-group.text-center
              %h4 Your child profile image:
              .img-circle
                = profile_avatar_select(@child)
              = f.file_field :avatar, onChange: 'loadFile(event)'
        .row
          .col-md-12
            .form-group.text-center
              = f.input :name, label: false, placeholder: 'Child name', required: true
            .form-group.text-center
              = f.input :age, label: false, placeholder: 'Child age', required: true
        .form-group.text-center
          = f.button :submit, class: 'btn-success btn-block'

app/views/children/show.html.haml
= render 'layouts/return'

%h1
  = @child.name
  .number-circle
    = @child.age
  .text-center
    = profile_avatar_select(@child)

.col-md-8
  = month_calendar events: @tasks do |date, tasks|
    = date

    -tasks.each do |task|
      .text-center
        = render 'tasks/status', task: task
        = task.summary

.col-md-4
  - if @uncompleted_tasks.size > 0
    %h3
      = "Uncompleted tasks:"
    -@uncompleted_tasks.each do |task|
      = render 'tasks/task', task: task, child: @child
  - if @completed_tasks.size > 0
    %h3
      = "Completed tasks:"
    -@completed_tasks.each do |task|
      = render 'tasks/task', task: task, child: @child
  = link_to "Add task", new_parent_child_task_path(@child.parent, @child), class: "btn btn-primary btn-block"

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default
  .navbar-container
    .navar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle Navigation
        %span.icon-bar
        %span.icon-bar
      .navbar-brand
        = link_to "Children Supervisor", root_path
    .collapse.navbar-collapse#bs-navbar-collapse-1
      %ul.nav.navbar-nav.navbar-right
        - if parent_signed_in?
          %li
            = link_to "Sign Out", destroy_parent_session_path, method: :delete
        - else
          %li
            = link_to "Sign Up", new_parent_registration_path
          %li
            = link_to "Log In", new_parent_session_path

app/views/layouts/_return.html.haml
%h4
  .pull-right
    = link_to "Return", request.referer, class: "glyphicon glyphicon-chevron-left"

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Children Supervisor
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    = render 'layouts/navbar'

    - if parent_signed_in?
      .container
        .text-center
          - flash.each do |name, msg|
            = content_tag :div, msg, class: "alert"
        = yield
    - else
      .main-page-bg
        .container
          .text-center
            - flash.each do |name, msg|
              = content_tag :div, msg, class: "alert"
          = yield

app/views/pages/main.html.haml
.text-center
  %h1 Make an account
  %p And don't worry about your children anymore

app/views/parents/show.html.haml
.text-center
  %h1 Your children:

.children-wrapper
  -@children.each do |child|
    .list-group
      .list-group-item
        .children-image
          = profile_avatar_select(child)
        = link_to child.name + " - " + child.age.to_s, parent_child_path(@parent, child)
        .pull-right
          <strong>Tasks number: </strong>
          = child.tasks.count
  = link_to "Add child", new_parent_child_path(@parent), class: "btn btn-success btn-block"

app/views/tasks/_form.html.haml
= render 'layouts/return'

.children-wrapper
  = simple_form_for @task, url: parent_child_tasks_path, html: { multipart: true } do |f|
    .row
      .col-md-12.text-center
        = f.error_notification
    .container-fluid
      .form-group.text-center
        = f.input :summary, placeholder: 'Input taks summary...'
      .form-group.text-center
        = f.input :description, as: :text, placeholder: 'Input task decription...'
      .form-group.text-center
        = f.button :submit, class: 'btn-primary btn-block'

app/views/tasks/_rate.html.haml
.text-center
  = imdb_style_rating_for @task, current_parent
  = rating_for @task, 'mark'

app/views/tasks/_status.html.haml
-if task.status
  %span(class="glyphicon glyphicon-ok-circle green")
-else
  %span(class="glyphicon glyphicon-remove-circle red")

app/views/tasks/_task.html.haml
.list-group
  .list-group-item
    = link_to task.summary, parent_child_task_path(child.parent, child, task.id)
    .pull-right
      = render 'tasks/status', task: task

app/views/tasks/new.html.haml
= render 'form'

app/views/tasks/show.html.haml
= render 'layouts/return'

%h1
  = @task.summary
  = render 'rate'

.children-wrapper
  .child
    .row
      = @task.description